spring:
  h2:
    console: enabled=true
  datasource:
    url: jdbc:h2:mem:StromDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
#  data:
#    rest:
#      base-path: /api

okta:
  oauth2:
    issuer: https://dev-997043.oktapreview.com/oauth2/default
    clientId: 0oahwknrm8TqD3gYt0h7
    audience: api://default
    clientSecret: wATAzBWHlzuKalwj9uGI-horPN3LBzzUDI4eERsN
    scopeClaim: scp
    rolesClaim: groups
#    accessTokenUri: https://dev-997043.oktapreview.com/oauth2/default/v1/token
#    userAuthorizationUri: https://dev-997043.oktapreview.com/oauth2/default/v1/authorize

#logging:
#  level: info

#server:
#  context-path: /strommaler
  ## http://localhost:8080/strommaaler/h2-console

  #spring.profiles.active=test
  ##server.port = 8022
  ##http://localhost:8080/strommaaler/swagger-ui.html
  #server.context-path: /strommaaler
  ## http://localhost:8080/strommaaler/h2-console

  # http://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot.html#boot-redis-configuration
  # spring.redis.host=localhost
  #spring.redis.password=secret
  # spring.redis.port=6379